# docker-compose.yml
version: '3.8'

services:
  api:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
    command: npm run dev

  test:
    build: .
    volumes:
      - ./src:/app/src
    command: npm run test:watch